(in-package :focus)

;;; Static file serving

(defun guess-content-type (path)
  "Guess content type from file extension."
  (let ((ext (pathname-type (pathname path))))
    (cond
      ((string= ext "html") "text/html")
      ((string= ext "css") "text/css")
      ((string= ext "js") "application/javascript")
      ((string= ext "json") "application/json")
      ((string= ext "png") "image/png")
      ((string= ext "jpg") "image/jpeg")
      ((string= ext "svg") "image/svg+xml")
      ((string= ext "ico") "image/x-icon")
      (t "application/octet-stream"))))

(defun serve-static-file (path)
  "Serve a static file from the configured static directory."
  (let* ((rel-path (if (and (plusp (length path))
                            (char= (char path 0) #\/))
                       (subseq path 1)
                       path))
         (root (config->static-dir *config*))
         (full-path (merge-pathnames rel-path root)))
    (if (and (probe-file full-path)
             (not (uiop:directory-pathname-p full-path)))
        (let ((content (with-open-file (s full-path :direction :input :element-type '(unsigned-byte 8))
                         (let ((data (make-array (file-length s) :element-type '(unsigned-byte 8))))
                           (read-sequence data s)
                           data))))
          (list 200
                `(:content-type ,(guess-content-type path)
                  :content-length ,(length content))
                (list content)))
        nil)))

;;; API Router

(defun router (env)
  "Route requests to handlers."
  (bind ((path (getf env :path-info))
         (method (getf env :request-method)))
    (cond
      ;; API routes
      ((ppcre:scan "^/api/" path)
       (route-api env path method))
      ;; Static files
       ((and (string= method "GET"))
        (or (serve-static-file path)
            (and (ppcre:scan "^/tickets/\\d+$" path)
                 (serve-static-file "index.html"))
            (and (ppcre:scan "^/tickets/\\d+/activity$" path)
                 (serve-static-file "index.html"))
            (and (string= path "/")
                 (serve-static-file "index.html"))
            (and (string= path "/settings")
                 (serve-static-file "index.html"))
            (error-response "Not found" 404)))
      ;; 404
      (t
       (error-response "Not found" 404)))))

(defun route-api (env path method)
  "Route API requests."
  (cond
    ;; Auth routes (public)
    ((and (string= path "/api/auth/login")
          (string= method "GET"))
     (handle-auth-login env))
    ((and (string= path "/api/auth/callback")
          (string= method "GET"))
     (handle-auth-callback env))
    ((and (string= path "/api/auth/me")
          (string= method "GET"))
     (handle-auth-me env))
    ((and (string= path "/api/auth/logout")
          (string= method "POST"))
     (handle-auth-logout env))
    ((and (string= path "/api/app/info")
          (string= method "GET"))
     (handle-app-info env))
    ;; Tickets - list and create (exact path)
    ((and (string= path "/api/tickets")
          (string= method "GET"))
     (handle-list-tickets env))
    ((and (string= path "/api/tickets")
          (string= method "POST"))
     (handle-create-ticket env))
    ;; Search must come before parameterized routes
    ((and (string= method "GET")
          (ppcre:scan "^/api/tickets/search" path))
     (handle-search-tickets env))
    ;; Ticket by ID (GET/PUT/DELETE)
    ((and (string= method "GET")
          (ppcre:scan "^/api/tickets/\\d+$" path))
     (handle-get-ticket env))
    ((and (string= method "PUT")
          (ppcre:scan "^/api/tickets/\\d+$" path))
     (handle-update-ticket env))
    ((and (string= method "DELETE")
          (ppcre:scan "^/api/tickets/\\d+$" path))
     (handle-delete-ticket env))
    ;; Comments
    ((and (string= method "GET")
          (ppcre:scan "^/api/tickets/\\d+/comments$" path))
     (handle-list-comments env))
    ((and (string= method "POST")
          (ppcre:scan "^/api/tickets/\\d+/comments$" path))
     (handle-create-comment env))
    ;; Activity
    ((and (string= method "GET")
          (ppcre:scan "^/api/tickets/\\d+/activity$" path))
     (handle-list-activity env))
    ;; Users
    ((and (string= path "/api/users")
          (string= method "GET"))
     (handle-list-users env))
    ((and (string= path "/api/users")
          (string= method "POST"))
     (handle-create-user env))
    ((and (string= method "PUT")
          (ppcre:scan "^/api/users/\\d+$" path))
     (handle-update-user env))
    ((and (string= method "DELETE")
          (ppcre:scan "^/api/users/\\d+$" path))
     (handle-delete-user env))
    ;; Labels
    ((and (string= path "/api/labels")
          (string= method "GET"))
     (handle-list-labels env))
    ((and (string= path "/api/labels")
          (string= method "POST"))
     (handle-create-label env))
    ;; Attachments
    ((and (string= method "GET")
          (ppcre:scan "^/api/attachments/\\d+$" path))
     (handle-get-attachment env))
    ;; Webhooks
    ((and (string= path "/api/webhooks")
          (string= method "GET"))
     (handle-list-webhooks env))
    ((and (string= path "/api/webhooks")
          (string= method "POST"))
     (handle-create-webhook env))
    ;; Groups - list and create (exact path)
    ((and (string= path "/api/groups")
          (string= method "GET"))
     (handle-list-groups env))
    ((and (string= path "/api/groups")
          (string= method "POST"))
     (handle-create-group env))
    ;; Ticket observers (before group routes to avoid conflict)
    ((and (string= method "GET")
          (ppcre:scan "^/api/tickets/\\d+/observers$" path))
     (handle-list-ticket-observers env))
    ((and (string= method "POST")
          (ppcre:scan "^/api/tickets/\\d+/observers$" path))
     (handle-add-ticket-observer env))
    ((and (string= method "DELETE")
          (ppcre:scan "^/api/tickets/\\d+/observers/.+$" path))
     (handle-remove-ticket-observer env))
    ;; Group by ID (GET/PUT/DELETE)
    ((and (string= method "GET")
          (ppcre:scan "^/api/groups/\\d+$" path))
     (handle-get-group env))
    ((and (string= method "PUT")
          (ppcre:scan "^/api/groups/\\d+$" path))
     (handle-update-group env))
    ((and (string= method "DELETE")
          (ppcre:scan "^/api/groups/\\d+$" path))
     (handle-delete-group env))
    ;; Group members
    ((and (string= method "GET")
          (ppcre:scan "^/api/groups/\\d+/members$" path))
     (handle-list-group-members env))
    ((and (string= method "POST")
          (ppcre:scan "^/api/groups/\\d+/members$" path))
     (handle-add-group-member env))
    ((and (string= method "DELETE")
          (ppcre:scan "^/api/groups/\\d+/members/\\d+$" path))
     (handle-remove-group-member env))
    ;; 404
    (t
     (error-response "Not found" 404))))
