;;; focus — ticket tracker
;;; Copyright (C) 2026 Azamat S. Kalimoulline <turtle@bazon.ru>
;;;
;;; This program is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;;;

(ql:quickload :cl-base64 :silent t)

(defparameter *static-dir* "build/static/")
(defparameter *output-file* "src/static-assets.lisp")

(defun abs-static-dir ()
  (uiop:ensure-absolute-pathname (uiop:ensure-directory-pathname *static-dir*)
                                 (uiop:getcwd)))

(defun list-static-files (dir)
  "Recursively list files under DIR."
  (let ((result '()))
    (labels ((walk (d)
               (dolist (entry (uiop:directory-files d))
                 (push entry result))
               (dolist (sub (uiop:subdirectories d))
                 (walk sub))))
      (walk (uiop:ensure-directory-pathname dir)))
    (sort result #'string< :key #'file-namestring)))

(defun read-file-bytes (file)
  "Read a file as an octet vector."
  (with-open-file (s file :direction :input :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length s) :element-type '(unsigned-byte 8))))
      (read-sequence data s)
      data)))

(defun rel-path (file)
  "Path of FILE relative to *static-dir*."
  (uiop:enough-pathname file (abs-static-dir)))

(defun build-static-assets ()
  "Build static-assets.lisp from build/static/ files."
  (ensure-directories-exist *output-file*)
  (with-open-file (stream *output-file* :direction :output :if-exists :supersede)
    (format stream ";;; focus — ticket tracker~%")
    (format stream ";;; Copyright (C) 2026 Azamat S. Kalimoulline <turtle@bazon.ru>~%")
    (format stream ";;;~%")
    (format stream ";;; This program is free software: you can redistribute it and/or modify~%")
    (format stream ";;; it under the terms of the GNU General Public License as published by~%")
    (format stream ";;; the Free Software Foundation, either version 3 of the License, or~%")
    (format stream ";;; (at your option) any later version.~%")
    (format stream ";;;~%")
    (format stream ";;; This program is distributed in the hope that it will be useful,~%")
    (format stream ";;; but WITHOUT ANY WARRANTY; without even the implied warranty of~%")
    (format stream ";;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the~%")
    (format stream ";;; GNU General Public License for more details.~%")
    (format stream ";;;~%")
    (format stream ";;; You should have received a copy of the GNU General Public License~%")
    (format stream ";;; along with this program.  If not, see <https://www.gnu.org/licenses/>.~%")
    (format stream ";;;~%~%")
    (format stream "(in-package :focus)~%~%")
    (format stream ";;; Generated by tools/build-static.lisp — do not edit manually.~%~%")
    (format stream "(defparameter *static-assets*~%  '(~%")
    (dolist (file (list-static-files *static-dir*))
      (let ((path (rel-path file))
            (b64 (cl-base64:usb8-array-to-base64-string (read-file-bytes file) :columns 0)))
        (format stream "    (\"~a\" . \"~a\")~%" path b64)))
    (format stream "    ))~%"))
  (format t "Generated ~a~%" *output-file*))

(build-static-assets)
(uiop:quit)
