;;; focus — ticket tracker
;;; Copyright (C) 2026 Azamat S. Kalimoulline <turtle@bazon.ru>
;;;
;;; This program is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;;;

(defparameter *project-name* "focus")
(defparameter *migrations-dir* "migrations/")
(defparameter *output-file* "src/migrations.lisp")

(defun get-migration-files ()
  "Get all migration files sorted by name."
  (sort (directory (format nil "~a*.up.sql" *migrations-dir*))
        #'string<
        :key #'file-namestring))

(defun read-migration-file (file)
  "Read a migration file and return its contents."
  (with-open-file (stream file :direction :input)
    (let ((contents (make-string (file-length stream))))
      (read-sequence contents stream)
      contents)))

(defun extract-version (filename)
  "Extract version number from migration filename."
  (subseq (file-namestring filename) 0 4))

(defun extract-name (filename)
  "Extract migration name from migration filename."
  (let ((name (file-namestring filename)))
    (subseq name 0 (- (length name) 8))))

(defun build-migrations ()
  "Build migrations.lisp from SQL files."
  (let ((migrations (get-migration-files)))
    (with-open-file (stream *output-file* :direction :output :if-exists :supersede)
      (format stream ";;; focus — ticket tracker~%")
      (format stream ";;; Copyright (C) 2026 Azamat S. Kalimoulline <turtle@bazon.ru>~%")
      (format stream ";;;~%")
      (format stream ";;; This program is free software: you can redistribute it and/or modify~%")
      (format stream ";;; it under the terms of the GNU General Public License as published by~%")
      (format stream ";;; the Free Software Foundation, either version 3 of the License, or~%")
      (format stream ";;; (at your option) any later version.~%")
      (format stream ";;;~%")
      (format stream ";;; This program is distributed in the hope that it will be useful,~%")
      (format stream ";;; but WITHOUT ANY WARRANTY; without even the implied warranty of~%")
      (format stream ";;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the~%")
      (format stream ";;; GNU General Public License for more details.~%")
      (format stream ";;;~%")
      (format stream ";;; You should have received a copy of the GNU General Public License~%")
      (format stream ";;; along with this program.  If not, see <https://www.gnu.org/licenses/>.~%")
      (format stream ";;;~%~%")
      (format stream "(in-package :focus)~%~%")
      (format stream ";;; Generated by tools/build-migrations.lisp — do not edit manually.~%~%")
      (format stream "(defparameter *migrations*~%  '(~%")
      (dolist (migration migrations)
        (let* ((version (extract-version migration))
               (name (extract-name migration))
               (up-sql (read-migration-file migration))
               (down-file (merge-pathnames (make-pathname :type "down.sql")
                                           migration))
               (down-sql (when (probe-file down-file)
                           (read-migration-file down-file))))
          (format stream "    (\"~a-~a\"~%" version name)
          (format stream "     :up ~s~%" up-sql)
          (when down-sql
            (format stream "     :down ~s~%" down-sql))
          (format stream ")~%")))
      (format stream "))~%"))
    (format t "Generated ~a~%" *output-file*)))

(build-migrations)
