(ql:quickload :cl-base64 :silent t)

(defparameter *static-dir* "build/static/")
(defparameter *output-file* "src/static-assets.lisp")

(defun abs-static-dir ()
  (uiop:ensure-absolute-pathname (uiop:ensure-directory-pathname *static-dir*)
                                 (uiop:getcwd)))

(defun list-static-files (dir)
  "Recursively list files under DIR."
  (let ((result '()))
    (labels ((walk (d)
               (dolist (entry (uiop:directory-files d))
                 (push entry result))
               (dolist (sub (uiop:subdirectories d))
                 (walk sub))))
      (walk (abs-static-dir)))
    (sort result #'string< :key #'file-namestring)))

(defun read-file-bytes (file)
  "Read a file as an octet vector."
  (with-open-file (s file :direction :input :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length s) :element-type '(unsigned-byte 8))))
      (read-sequence data s)
      data)))

(defun rel-path (file)
  "Path of FILE relative to *static-dir*."
  (uiop:enough-pathname file (abs-static-dir)))

(defun build-static-assets ()
  "Build static-assets.lisp from build/static/ files."
  (ensure-directories-exist *output-file*)
  (with-open-file (stream *output-file* :direction :output :if-exists :supersede)
    (format stream "(in-package :focus)~%~%")
    (format stream ";;; Generated by tools/build-static.lisp — do not edit manually.~%~%")
    (format stream "(defparameter *static-assets*~%  '(~%")
    (dolist (file (list-static-files *static-dir*))
      (let ((path (rel-path file))
            (b64 (cl-base64:usb8-array-to-base64-string (read-file-bytes file) :columns 0)))
        (format stream "    (\"~a\" . \"~a\")~%" path b64)))
    (format stream "    ))~%"))
  (format t "Generated ~a~%" *output-file*))

(build-static-assets)
