;;; focus — ticket tracker
;;; Copyright (C) 2026 Azamat S. Kalimoulline <turtle@bazon.ru>
;;;
;;; This program is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;;;

(in-package :focus)

;;; Generated by tools/build-migrations.lisp — do not edit manually.

(defparameter *migrations*
  '(
    ("0001-0001-schema-versio"
     :up "CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT now()
);
"
)
    ("0002-0002-users-tabl"
     :up "CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);
"
)
    ("0003-0003-issues-tabl"
     :up "CREATE TABLE IF NOT EXISTS issues (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'open',
    priority VARCHAR(10) DEFAULT 'medium',
    assignee_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);
CREATE INDEX IF NOT EXISTS idx_issues_priority ON issues(priority);
CREATE INDEX IF NOT EXISTS idx_issues_assignee_id ON issues(assignee_id);
"
)
    ("0004-0004-labels-tabl"
     :up "CREATE TABLE IF NOT EXISTS labels (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) DEFAULT '#3498db'
);
"
)
    ("0005-0005-issue-label"
     :up "CREATE TABLE IF NOT EXISTS issue_labels (
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    label_id INTEGER REFERENCES labels(id) ON DELETE CASCADE,
    PRIMARY KEY (issue_id, label_id)
);

CREATE INDEX IF NOT EXISTS idx_issue_labels_issue_id ON issue_labels(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_labels_label_id ON issue_labels(label_id);
"
)
    ("0006-0006-comments-tabl"
     :up "CREATE TABLE IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_issue_id ON comments(issue_id);
"
)
    ("0007-0007-activity-tabl"
     :up "CREATE TABLE IF NOT EXISTS activity (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    action VARCHAR(50) NOT NULL,
    details JSONB,
    created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_issue_id ON activity(issue_id);
"
)
    ("0008-0008-attachments-tabl"
     :up "CREATE TABLE IF NOT EXISTS attachments (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    size INTEGER,
    data BYTEA,
    created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attachments_issue_id ON attachments(issue_id);
"
)
    ("0009-0009-webhooks-tabl"
     :up "CREATE TABLE IF NOT EXISTS webhooks (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    secret VARCHAR(255),
    events TEXT[] DEFAULT '{}',
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT now()
);
"
)
    ("0010-0010-sessions-tabl"
     :up "CREATE TABLE sessions (
    id VARCHAR(64) PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT now(),
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sessions_expires ON sessions(expires_at);
"
)
    ("0011-0011-issues-positio"
     :up "ALTER TABLE issues ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0;

UPDATE issues SET position = sub.new_pos
FROM (
  SELECT id, ROW_NUMBER() OVER (PARTITION BY status ORDER BY created_at DESC) - 1 AS new_pos
  FROM issues
) AS sub
WHERE issues.id = sub.id;
"
)
    ("0012-0012-rename-issues-to-ticket"
     :up "-- Drop foreign keys first, rename, then recreate
ALTER TABLE issue_labels DROP CONSTRAINT issue_labels_issue_id_fkey;
ALTER TABLE comments DROP CONSTRAINT comments_issue_id_fkey;
ALTER TABLE activity DROP CONSTRAINT activity_issue_id_fkey;
ALTER TABLE attachments DROP CONSTRAINT attachments_issue_id_fkey;

ALTER TABLE issue_labels RENAME TO ticket_labels;
ALTER TABLE ticket_labels RENAME COLUMN issue_id TO ticket_id;
ALTER INDEX idx_issue_labels_issue_id RENAME TO idx_ticket_labels_ticket_id;
ALTER INDEX idx_issue_labels_label_id RENAME TO idx_ticket_labels_label_id;

ALTER TABLE comments RENAME COLUMN issue_id TO ticket_id;
ALTER TABLE activity RENAME COLUMN issue_id TO ticket_id;
ALTER TABLE attachments RENAME COLUMN issue_id TO ticket_id;

ALTER TABLE issues RENAME TO tickets;

ALTER TABLE ticket_labels ADD CONSTRAINT ticket_labels_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE ticket_labels ADD CONSTRAINT ticket_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels(id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE activity ADD CONSTRAINT activity_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD CONSTRAINT attachments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
"
)
    ("0013-0013-fractional-positionin"
     :up "ALTER TABLE tickets ADD COLUMN position_num INTEGER DEFAULT 0;
ALTER TABLE tickets ADD COLUMN position_den INTEGER DEFAULT 1;

UPDATE tickets SET position_num = position, position_den = 1;

ALTER TABLE tickets DROP COLUMN position;
"
)
    ("0014-0014-ticket-colo"
     :up "ALTER TABLE tickets ADD COLUMN color VARCHAR(7) DEFAULT '#6b7280';"
)
    ("0015-0015-user-pictur"
     :up "ALTER TABLE users ADD COLUMN picture VARCHAR(500);
"
)
    ("0016-0016-groups-and-observer"
     :up "CREATE TABLE groups (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE group_members (
    group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

CREATE INDEX idx_group_members_group ON group_members(group_id);
CREATE INDEX idx_group_members_user ON group_members(user_id);

ALTER TABLE tickets ADD COLUMN assignee_type VARCHAR(20) DEFAULT 'user';

CREATE TABLE ticket_observers (
    ticket_id INTEGER REFERENCES tickets(id) ON DELETE CASCADE,
    observer_type VARCHAR(20) NOT NULL CHECK (observer_type IN ('user', 'group')),
    observer_id INTEGER NOT NULL,
    PRIMARY KEY (ticket_id, observer_type, observer_id)
);

CREATE INDEX idx_ticket_observers_ticket ON ticket_observers(ticket_id);
"
)
    ("0017-0017-user-rol"
     :up "ALTER TABLE users ADD COLUMN role VARCHAR(20) DEFAULT 'user';
UPDATE users SET role = 'admin' WHERE id = 1;
"
)
    ("0018-0018-polymorphic-assigne"
     :up "ALTER TABLE tickets DROP CONSTRAINT IF EXISTS issues_assignee_id_fkey;"
)
    ("0019-0019-boards-lifecycl"
     :up "CREATE TABLE boards (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'common',
    is_default BOOLEAN NOT NULL DEFAULT false,
    owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE board_members (
    board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
    member_type VARCHAR(20) NOT NULL CHECK (member_type IN ('user', 'group')),
    member_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (board_id, member_type, member_id)
);

CREATE TABLE board_statuses (
    id SERIAL PRIMARY KEY,
    board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) DEFAULT '#6b7280',
    position INTEGER DEFAULT 0,
    UNIQUE (board_id, code)
);

CREATE TABLE board_transitions (
    id SERIAL PRIMARY KEY,
    board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
    from_code VARCHAR(50) NOT NULL,
    to_code VARCHAR(50) NOT NULL,
    UNIQUE (board_id, from_code, to_code)
);

ALTER TABLE tickets ADD COLUMN board_id INTEGER REFERENCES boards(id) ON DELETE SET NULL;
CREATE INDEX idx_tickets_board ON tickets (board_id);

INSERT INTO boards (name, type, is_default) VALUES ('Common', 'common', true);

INSERT INTO board_statuses (board_id, code, name, color, position) VALUES
  (currval('boards_id_seq'), 'backlog', 'Backlog', '#6b7280', 0),
  (currval('boards_id_seq'), 'open', 'Open', '#3b82f6', 1),
  (currval('boards_id_seq'), 'in_progress', 'In Progress', '#f59e0b', 2),
  (currval('boards_id_seq'), 'review', 'Review', '#8b5cf6', 3),
  (currval('boards_id_seq'), 'done', 'Done', '#10b981', 4);

INSERT INTO board_transitions (board_id, from_code, to_code) VALUES
  (currval('boards_id_seq'), 'backlog', 'open'),
  (currval('boards_id_seq'), 'open', 'in_progress'),
  (currval('boards_id_seq'), 'open', 'done'),
  (currval('boards_id_seq'), 'in_progress', 'review'),
  (currval('boards_id_seq'), 'in_progress', 'open'),
  (currval('boards_id_seq'), 'review', 'done'),
  (currval('boards_id_seq'), 'review', 'in_progress'),
  (currval('boards_id_seq'), 'done', 'open');

UPDATE tickets SET board_id = (SELECT id FROM boards WHERE is_default LIMIT 1)
WHERE board_id IS NULL;"
)
    ("0020-0020-boards-default-lifecycl"
     :up "INSERT INTO board_transitions (board_id, from_code, to_code)
SELECT b.id, tr.from_code, tr.to_code
FROM boards b
CROSS JOIN (VALUES
    ('backlog', 'open'),
    ('open', 'in_progress'),
    ('open', 'done'),
    ('in_progress', 'review'),
    ('in_progress', 'open'),
    ('review', 'done'),
    ('review', 'in_progress'),
    ('done', 'open')
) AS tr(from_code, to_code)
WHERE NOT EXISTS (
    SELECT 1 FROM board_transitions bt WHERE bt.board_id = b.id
);

INSERT INTO board_statuses (board_id, code, name, color, position)
SELECT b.id, s.code, s.name, s.color, s.position
FROM boards b
CROSS JOIN (VALUES
    ('backlog', 'Backlog', '#6b7280', 0),
    ('open', 'Open', '#3b82f6', 1),
    ('in_progress', 'In Progress', '#f59e0b', 2),
    ('review', 'Review', '#8b5cf6', 3),
    ('done', 'Done', '#10b981', 4)
) AS s(code, name, color, position)
WHERE NOT EXISTS (
    SELECT 1 FROM board_statuses bs WHERE bs.board_id = b.id
);"
)
    ("0021-0021-users-soft-delet"
     :up "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS idx_users_is_deleted ON users(is_deleted);
"
)
    ("0022-0022-board-status-load-coun"
     :up "ALTER TABLE board_statuses ADD COLUMN IF NOT EXISTS load_count INTEGER NOT NULL DEFAULT 20;
UPDATE board_statuses SET load_count = 5 WHERE code = 'done';"
)
))
