(in-package :focus)

;;; Generated by tools/build-migrations.lisp — do not edit manually.

(defparameter *migrations*
  '(
    ("0001-0001-schema-versio"
     :up "CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT now()
);
"
)
    ("0002-0002-users-tabl"
     :up "CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);
"
)
    ("0003-0003-issues-tabl"
     :up "CREATE TABLE IF NOT EXISTS issues (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'open',
    priority VARCHAR(10) DEFAULT 'medium',
    assignee_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);
CREATE INDEX IF NOT EXISTS idx_issues_priority ON issues(priority);
CREATE INDEX IF NOT EXISTS idx_issues_assignee_id ON issues(assignee_id);
"
)
    ("0004-0004-labels-tabl"
     :up "CREATE TABLE IF NOT EXISTS labels (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) DEFAULT '#3498db'
);
"
)
    ("0005-0005-issue-label"
     :up "CREATE TABLE IF NOT EXISTS issue_labels (
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    label_id INTEGER REFERENCES labels(id) ON DELETE CASCADE,
    PRIMARY KEY (issue_id, label_id)
);

CREATE INDEX IF NOT EXISTS idx_issue_labels_issue_id ON issue_labels(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_labels_label_id ON issue_labels(label_id);
"
)
    ("0006-0006-comments-tabl"
     :up "CREATE TABLE IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_issue_id ON comments(issue_id);
"
)
    ("0007-0007-activity-tabl"
     :up "CREATE TABLE IF NOT EXISTS activity (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    action VARCHAR(50) NOT NULL,
    details JSONB,
    created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_issue_id ON activity(issue_id);
"
)
    ("0008-0008-attachments-tabl"
     :up "CREATE TABLE IF NOT EXISTS attachments (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    size INTEGER,
    data BYTEA,
    created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attachments_issue_id ON attachments(issue_id);
"
)
    ("0009-0009-webhooks-tabl"
     :up "CREATE TABLE IF NOT EXISTS webhooks (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    secret VARCHAR(255),
    events TEXT[] DEFAULT '{}',
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT now()
);
"
)
    ("0010-0010-sessions-tabl"
     :up "CREATE TABLE sessions (
    id VARCHAR(64) PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT now(),
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sessions_expires ON sessions(expires_at);
"
)
    ("0011-0011-issues-positio"
     :up "ALTER TABLE issues ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0;

UPDATE issues SET position = sub.new_pos
FROM (
  SELECT id, ROW_NUMBER() OVER (PARTITION BY status ORDER BY created_at DESC) - 1 AS new_pos
  FROM issues
) AS sub
WHERE issues.id = sub.id;
"
)
    ("0012-0012-rename-issues-to-ticket"
     :up "-- Drop foreign keys first, rename, then recreate
ALTER TABLE issue_labels DROP CONSTRAINT issue_labels_issue_id_fkey;
ALTER TABLE comments DROP CONSTRAINT comments_issue_id_fkey;
ALTER TABLE activity DROP CONSTRAINT activity_issue_id_fkey;
ALTER TABLE attachments DROP CONSTRAINT attachments_issue_id_fkey;

ALTER TABLE issue_labels RENAME TO ticket_labels;
ALTER TABLE ticket_labels RENAME COLUMN issue_id TO ticket_id;
ALTER INDEX idx_issue_labels_issue_id RENAME TO idx_ticket_labels_ticket_id;
ALTER INDEX idx_issue_labels_label_id RENAME TO idx_ticket_labels_label_id;

ALTER TABLE comments RENAME COLUMN issue_id TO ticket_id;
ALTER TABLE activity RENAME COLUMN issue_id TO ticket_id;
ALTER TABLE attachments RENAME COLUMN issue_id TO ticket_id;

ALTER TABLE issues RENAME TO tickets;

ALTER TABLE ticket_labels ADD CONSTRAINT ticket_labels_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE ticket_labels ADD CONSTRAINT ticket_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels(id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE activity ADD CONSTRAINT activity_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD CONSTRAINT attachments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
"
)
    ("0013-0013-fractional-positionin"
     :up "ALTER TABLE tickets ADD COLUMN position_num INTEGER DEFAULT 0;
ALTER TABLE tickets ADD COLUMN position_den INTEGER DEFAULT 1;

UPDATE tickets SET position_num = position, position_den = 1;

ALTER TABLE tickets DROP COLUMN position;
"
)
    ("0014-0014-ticket-colo"
     :up "ALTER TABLE tickets ADD COLUMN color VARCHAR(7) DEFAULT '#6b7280';"
)
))
